### ISSUE TITLE
使用mapbox作为地球图的贴图

### ISSUE THREAD

**Issue by hon** [ecomfe/echarts-gl#106]
请问可以使用mapbox在线地图作为地球图的贴图吗？ 并且操作上也能将二者的经纬度坐标对应。就像google earth那样。我尝试了吧mapbox和global配置项配置了以下，好像不起作用。问一下，二者集成在技术上是否可行。

**Comment by pissang** [comment]
这个没法做到，暂时也没有这方面升级的计划
