### ISSUE TITLE
echarts环形图问题

### ISSUE THREAD

**Issue by huanledeniuduzi** [ecomfe/echarts-gl#111]
用echarts绘制环形图时，遇到一个问题：
环形图中的百分比文字不能垂直居中，不知道该如何设置。请问要如何设置？
不清楚的话请看下图。矩形框框里的文字没有垂直居中。
谢谢！
![11](https://user-images.githubusercontent.com/30464088/29115097-ebeea82a-7d28-11e7-9a1b-160da504cc30.png)

**Comment by pissang** [comment]
echarts 相关问题在 https://github.com/ecomfe/echarts 这里提问
