### ISSUE TITLE
请问以后的更新中能考虑直接将echarts-gl直接绘制到mapbox实例上么？

### ISSUE THREAD

**Issue by liujiusheng** [ecomfe/echarts-gl#113]
echarts-gl很好用也很炫酷，mapbox-gl做的地图很好看，可是毕竟echarts更侧重于做炫酷的展示而不是着重于做交互，如果能将echart直接绘制到mapbox-gl生成的实例上，那么复杂的交互就有可能实现，挺期待echarts-gl能提供这样的支持。

**Comment by pissang** [comment]
首先我们是没办法直接画到 mapbox-gl 生成的实例上的，然后 echarts-gl 的展现和交互跟 mapbox-gl 是同步的，比如 mapbox-gl 的各种摄像机动画都会跟 echarts-gl 同步，不知道你指的复杂的交互是啥

**Comment by liujiusheng** [comment]
谢谢回答。复杂交互的话，比如说:要点击mapbox-gl里面的某个要素。现在mapbox-gl好像只能作为底图进行浏览,我现在如果要调用mapbox-gl官方api来改变底图样式就不知道怎么弄。

**Comment by pissang** [comment]
@liujiusheng 参考下 https://github.com/ecomfe/echarts-gl/issues/116#issuecomment-324517640 这个？

**Comment by liujiusheng** [comment]
@pissang 谢谢。就是要这东西。
