### ISSUE TITLE
关于在mapbox模式下camera平滑转换的实现

### ISSUE THREAD

**Issue by liveangela** [ecomfe/echarts-gl#116]
目前在geo3D和grid3D模式下，可直接使用viewControl来平滑地调整camera各项参数，这点在官方示例中已经实现（[Music Visualization](http://gallery.echartsjs.com/editor.html?c=xBkkLDElkZ)）

另外，官方还提供了通过series->map3D->viewControl来实现同样的效果，比如在实例[Buildings](http://gallery.echartsjs.com/editor.html?c=xHyVK5fcTl)的series下，对viewControl添加autoRotate: true字段即可实现自动旋转

问题在于，使用mapbox模式后，viewControl失效了，上述两种方法都不行。
那么如何在mapbox模式下做出类似的camera平滑动画的效果呢？

<hr>

做过一种尝试：高频率地更改mapbox下的center、zoom、pitch等属性，但是动画卡顿并不平滑。
其实mapbox的官网中有提供相应的[API](https://www.mapbox.com/mapbox-gl-js/api/#map#easeto)，不知道是否有引入，或者将mapbox的实例暴露出来，以便更直接地使用mapbox本身功能。

可能已有实现方法，但是没能发现，还望指正~
希望能获得帮助，不胜感激~

**Comment by pissang** [comment]
可以通过下面代码获取到 mapbox 实例
```
var mapbox = chart.getModel().getComponent('mapbox').getMapbox();
```
然后调用 `mapbox.flyTo` 方法实现镜头动画，也可以调用其它的方法

**Comment by liveangela** [comment]
@pissang 感谢P大，完美解决

**Comment by wuzhuorui5** [comment]
谢谢！
