### ISSUE TITLE
formatter:  value +1  ，都会显示 字串串接，而非数值+1 ?

### ISSUE THREAD

**Issue by RoxetteI** [ecomfe/echarts-gl#118]
以下代码都会显示 字串串接，而非数值+1 ? 
value=1 , 呈现时需要+1,   但是以下代码会显示: 2017/11
要如何写成把value值+1 ，而变成2017/2 

                    formatter: function (value) {
                        return '2017/' + parseInt(value)+1  + '月'; //显示 2017/11 ,而非 2017/2
                    }

以上问题，谢谢。

**Comment by pissang** [comment]
```js
return '2017/' + (parseInt(value)+1)  + '月'
```

**Comment by RoxetteI** [comment]
Thanks!
