### ISSUE TITLE
gird3D 的坐标轴标签 axisLabel 设置颜色不起作用

### ISSUE THREAD

**Issue by zengkan0703** [ecomfe/echarts-gl#121]
你好，在我使用 echarts-gl 过程中发现下面这个问题：

在官网的示例中给坐标轴或者 gird3D 的 axisLabel 设置 color 都不起作用。
示例地址： http://gallery.echartsjs.com/editor.html?c=xrJ5XyZ5px
`axisLabel: {
            textStyle: {
                color: '#ccc'
            }
        }`
不知道是不是我使用有问题，希望能够得到答复，谢谢。

**Comment by lichchao** [comment]
楼主最后找到了解决方案了吗？
也遇到了同样的问题，刚刚也提了个类似的issue #125

**Comment by pissang** [comment]
这个是 echarts 版本升级带来的问题，马上发的新版本会解决这个问题

**Comment by lichchao** [comment]
有没有暂时的hack可以用？比如改一下源码里的某个颜色属性值？

**Comment by pissang** [comment]
@lichchao 最新版本已经 build 了 https://github.com/ecomfe/echarts-gl/tree/master/dist ，如果是 npm 的话今天晚上发

**Comment by lichchao** [comment]
perfect！问题已解决。谢谢@pissang
