### ISSUE TITLE
Can the bar3D show inner label on each bar?

### ISSUE THREAD

**Issue by xiguaxigua** [ecomfe/echarts-gl#128]
### One-line summary [问题简述]
As the [example](https://jsfiddle.net/vue_echarts/bq53s6yw/), I want to add label on each bar, but text was covered by upper bar and what I can do is just change the opacity. So, can the bar add inner text?

![2017-09-13 3 00 40](https://user-images.githubusercontent.com/9931685/30363854-5338b486-9894-11e7-885e-804c5b23400e.png)

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]: 3.7.1
+ ECharts-gl version [ECharts 版本]: 1.0.0
+ Browser version [浏览器类型和版本]: Chrome 60
+ OS Version [操作系统类型和版本]: Macos

### Expected behaviour [期望结果]

add inner text on the bar

### ECharts option [ECharts配置项]

```javascript
option = {

  legend: {
    data: ['a', 'b', 'c', 'd']
  },
  xAxis3D: {
    type: 'value',
    show: false
  },
  yAxis3D: {
    type: 'value',
  },
  zAxis3D: {
    type: 'value',
  },
  grid3D: {
    show: false,
    viewControl: {
      // zoomSensitivity: 0,
      // rotateSensitivity: 0,
      // panSensitivity: 0,
      animation: false,
      panMouseButton: 'right'
    },
    light: {
      main: {
        shadow: true,
        quality: 'ultra',
        intensity: 1.5
      }
    }
  },
  series: [
    {
      type: 'bar3D',
      label: {
        show: true,
        distance: 2,
        textStyle: {
          color: '#000'
        }
      },
      itemStyle: {
        opacity: 0.8
      },
      name: 'a',
      shading: 'lambert',
      stack: 'stack',
      data: [
        [0, 10, 10]
      ]
    },
    {
      type: 'bar3D',
      label: {
        show: true,
        distance: 2,
        textStyle: {
          color: '#000'
        }
      },
      itemStyle: {
        opacity: 0.8
      },
      name: 'b',
      shading: 'lambert',
      stack: 'stack',
      data: [
        [0, 10, 20]
      ]
    }
  ]
}

```

### Other comments [其他信息]

https://jsfiddle.net/vue_echarts/bq53s6yw/

**Comment by xiguaxigua** [comment]
And what's the bast way to change bar3D to horizontal as [baidu tongji](http://tongji.baidu.com/data/browser)

**Comment by pissang** [comment]
About the label, will put all the labels in front of bars next version. Horizontal bar3D is  in plan.

**Comment by xiguaxigua** [comment]
Thank you
