### ISSUE TITLE
请问怎么获得mapbox对象？

### ISSUE THREAD

**Issue by adsort** [ecomfe/echarts-gl#132]
按照官网的example（http://gallery.echartsjs.com/editor.html?c=xBk24a33iW），已成功显示，但目前文档还比较薄弱，不知道怎么取得mapbox的map。。。比如，我需要map.setBearing(45)，这种怎么弄？

**Comment by jingsam** [comment]
https://github.com/ecomfe/echarts-gl/issues/116#issuecomment-324517640

**Comment by adsort** [comment]
哇~好快，谢谢

**Comment by jingsam** [comment]
最好提问之前先搜一下 😄
