### ISSUE TITLE
zip中是不是缺失文件

### ISSUE THREAD

**Issue by guoxulong** [ecomfe/echarts-gl#135]
大神，你data中是不是少给了几个资源，buildings-capetown.shp，buildings-capetown.dbf

**Comment by knowbyyou** [comment]
请问这个问题如何解决的？？

**Comment by pissang** [comment]
@guoxulong @knowbyyou 之前觉得这两个文件有点大就没传，已上传，也可以从 http://gallery.echartsjs.com/editor.html?c=xrJHCfsfE- 获取
