### ISSUE TITLE
geo3DCreator.js?8935:92 Uncaught ReferenceError: __DEV__ is not defined

### ISSUE THREAD

**Issue by enozr** [ecomfe/echarts-gl#140]
![image](https://user-images.githubusercontent.com/10611753/32985528-4edde6d4-ccf8-11e7-9001-d0fae7752707.png)
geo3DCreator.js?8935:92 Uncaught ReferenceError: __DEV__ is not defined
    at eval (geo3DCreator.js?8935:92)

echarts-gl version: "1.0.0-beta.5",
echarts version: "3.8.5",

**Comment by ludejun** [comment]
yes, i also get this problem when i "npm install" again.
![image](https://user-images.githubusercontent.com/5129913/33252741-eaf63264-d37a-11e7-9279-d624b361f19e.png)
But in the old node_modules, it's ok:
![image](https://user-images.githubusercontent.com/5129913/33252782-17b3d72a-d37b-11e7-9333-3e1f959a3c19.png)
Really?

**Comment by pissang** [comment]
Thanks for the report @ludejun @enozr . Will fix this issue in next release.

**Comment by pissang** [comment]
Hi, @ludejun @enozr. Just want to confirm have you configure the `alias` of `echarts` in webpack?

**Comment by ludejun** [comment]
no

**Comment by pissang** [comment]
@ludejun @enozr  Fixed in 1.0.0-beta.6

**Comment by VenkatRagven** [comment]
still error persists in 1.0.0-beta.6

**Comment by ludejun** [comment]
@VenkatRagven i'm ok now. Show your error and version?

**Comment by VenkatRagven** [comment]
![image](https://user-images.githubusercontent.com/12658765/33752387-90da3402-dc07-11e7-9df1-cd42511f0107.png)

**Comment by pissang** [comment]
@VenkatRagven How do you include the ECharts

**Comment by VenkatRagven** [comment]
currently i'm following [this link](https://xieziyu.github.io/ngx-echarts/#/home) to include echarts.

**Comment by z-park** [comment]
![image](https://user-images.githubusercontent.com/16479343/57608011-d2987480-759e-11e9-947a-912d70b0567b.png)
![image](https://user-images.githubusercontent.com/16479343/57608027-dd530980-759e-11e9-8d3d-ccda3278c351.png)

**Comment by Earlzs** [comment]
I have the same problem
