### ISSUE TITLE
bar 3d xAxis3D里的data 为‘200’时不能被当做字符串来匹配？

### ISSUE THREAD

**Issue by liuchengss** [ecomfe/echarts-gl#142]
bar 3d xAxis3D里的data 为‘200’时不能被当做字符串来匹配？

**Comment by liuchengss** [comment]
就是说data里面传入的 '399' 类似这样的 会被自动转化为数值索引 399

**Comment by pissang** [comment]
参考 https://github.com/ecomfe/echarts-gl/issues/81

**Comment by liuchengss** [comment]
感谢大佬，问题已经解决！
