### ISSUE TITLE
globe配置好地球,series中添加地图类型的数据是浮在地球上,和echarts-x中的用法差别很大

### ISSUE THREAD

**Issue by yanaxua** [ecomfe/echarts-gl#155]
series: [{
          type: 'map',
          map: 'world',
          // 绘制完整尺寸的 echarts 实例
          top: 0, left: 0,
          right: 0, bottom: 0,
          boundingCoords: [[-180, 90], [180, -90]]
        }]

试过几种方法,觉得还是应该添加支持使用实际地图图片作为地图背景,同时能添加canvas实例制作轮廓线,
最好和echarts-x中方法一致
![snipaste_20171225_190247](https://user-images.githubusercontent.com/27625929/34338758-54eb8660-e9a6-11e7-9980-45712ab617bd.png)

**Comment by kelvinau** [comment]
我也在尝试用鼠标的 emphasis 在地球上
echarts-x有baseLayer并可以设置backgroundImage, 希望echarts-gl也可以提供

**Comment by pissang** [comment]
参考 http://gallery.echartsjs.com/editor.html?c=xrJWQzgc6e&v=4 和 http://gallery.echartsjs.com/editor.html?c=xByneRvJyW&v=3

**Comment by kelvinau** [comment]
第一个正是我想做的! 原来是用 Layers 的 texture 放 echart, 不是baseTexture, 谢谢!

**Comment by yanaxua** [comment]
如题
