### ISSUE TITLE
grid3D 坐标轴的位置可以进行调整吗

### ISSUE THREAD

**Issue by zengkan0703** [ecomfe/echarts-gl#156]
如题，需求是把 3d 坐标轴位置全部放在相对的另一边，试了一下在坐标轴配置中加 position 属性（echarts-2d 的配置）没有作用。
想问问有没有什么其他办法可以解决这个问题，非常感谢。

**Comment by pissang** [comment]
为了更好的展示效果，目前坐标轴位置是自适应的，暂时不能进行设置
