### ISSUE TITLE
使用mapbox地图的mychart调用clear(),dispose()方法都报错

### ISSUE THREAD

**Issue by sad-apple** [ecomfe/echarts-gl#163]
使用mapbox地图的mychart调用clear(),dispose()方法都报错，t.getZr(...).delLayer is not a function，
其他的echarts实例都可以调用清除方法，我要清除mapbox的mychart实例怎么操作

**Comment by pissang** [comment]
谢谢反馈，下个版本修复

**Comment by sad-apple** [comment]
请问下，现在这个echarts怎么释放内存

**Comment by pissang** [comment]
1.0.0 中应该已经修复这个问题了
