### ISSUE TITLE
rollup plugins are not declared as dev dependencies in package.json

### ISSUE THREAD

**Issue by jblabrousse** [ecomfe/echarts-gl#164]
Hi,

Roll up plugins are currently declared as dependencies and not dev dependencies. 
This is altering the usage of the library by pulling a lot of unwanted deps.

Thank you

**Comment by yzengm** [comment]
能帮忙看看能不能把Roll up plugins放到dev 的pendence 吗？
谢谢啦

**Comment by pissang** [comment]
Fixed now. Thanks for the report @yzengm @jblabrousse

**Comment by pissang** [comment]
1.0.1 is released.
