### ISSUE TITLE
3D世界地图内存溢出问题

### ISSUE THREAD

**Issue by sunny860201** [ecomfe/echarts-gl#18]
实现功能如下：
   我根据官网上的“World Flights”3D地图写了一个程序，每分钟请求一次数据库，大致100条数据，重新塞数据，在塞数据之前调用myChart.dispose()方法销毁，然后重新初始化，但是差不多20分钟的样子，火狐的浏览器内存就会飙升到2G左右，然后崩溃，请问如何解决？

**Comment by liujie20087349** [comment]
作者你好，我也遇到了3d 地图切换导致内存溢出的问题，我在gallary提交了一个简单的样例：http://gallery.echartsjs.com/editor.html?c=xHyL5_gEjW，本来我们是要做轮询34个省份的，但是每次在切换的时候，都会逐步增加大概5~10MB的内存
