### ISSUE TITLE
echartsGL绘制的时候,调用echarts.clear()方法清空报错

### ISSUE THREAD

**Issue by sunshine920103** [ecomfe/echarts-gl#181]
echartsGL绘制的时候,调用echarts.clear()方法清空报错，是GL中有了别的方法清空画布了吗？

**Comment by pissang** [comment]
怎么样的代码？报了什么错？

**Comment by sunshine920103** [comment]
你好，我们在使用echartsGL时，需要完成一个地图下钻的效果，但是从全国一级到了省一级之后，省份界面会显示全国的一个地图轮廓。我们初步怀疑是缓存的问题，然后通过设置了notMerge参数为true，可以解决轮廓问题，但是当点击全国地图的某个省之后就会控制台报错。
![image](https://user-images.githubusercontent.com/16233399/35549845-81dc4956-05c2-11e8-9069-dafa81880dfa.png)
跟踪进去之后是echart-gl-min.js文件的这段代码：
![image](https://user-images.githubusercontent.com/16233399/35549905-cbd0acbe-05c2-11e8-84fc-e2c8087e17c3.png)
![image](https://user-images.githubusercontent.com/16233399/35549914-d72d2c40-05c2-11e8-853c-3b1f55626500.png)

**Comment by pissang** [comment]
新发布的 1.0.2 已修复
