### ISSUE TITLE
globe 上 lines3d 绘制被遮挡，设置 globeOuterRadius 无效

### ISSUE THREAD

**Issue by kyriejoshua** [ecomfe/echarts-gl#184]
### 版本
echarts-gl: "1.0.0-beta.6",
echarts: "3.8.5",
chrome: 64

### 描述

在 globe 上绘制  lines3D, 线是自动生成的。目前的效果，似乎是距离越远，高度越高。
这里有一个 globeOuterRadius 配置用于限制高度，但在这里没有生效。

![globeouter](https://user-images.githubusercontent.com/16096736/35669264-771230f4-076f-11e8-90dd-dec876c9002b.png)

我的理解是将 globeOuterRadius 设置的较低，那 lines3D 的最大高度也应该变小。但是这里设置了没有效果，导致 lines3D 某些线过高，超出了可视区域。

### Option
// 部分数据如下
var dataLines = [{"fromName":"中国","toName":"A2","coords":[["120.19","30.26"],["-149","73"]]},{"fromName":"中国","toName":"A3","coords":[["120.19","30.26"],["-152","-19"]]},{"fromName":"中国","toName":"A4","coords":[["120.19","30.26"],["-94","-81"]]},{"fromName":"中国","toName":"A5","coords":[["120.19","30.26"],["-100","27"]]},{"fromName":"中国","toName":"A6","coords":[["120.19","30.26"],["26","18"]]},{"fromName":"中国","toName":"A7","coords":[["120.19","30.26"],["-131","3"]]},{"fromName":"中国","toName":"A8","coords":[["120.19","30.26"],["118","40"]]},{"fromName":"中国","toName":"A9","coords":[["120.19","30.26"],["141","-90"]]},{"fromName":"中国","toName":"A10","coords":[["120.19","30.26"],["-149","78"]]},{"fromName":"中国","toName":"A11","coords":[["120.19","30.26"],["-117","55"]]},{"fromName":"中国","toName":"A12","coords":[["120.19","30.26"],["54","-60"]]},{"fromName":"中国","toName":"A13","coords":[["120.19","30.26"],["84","-72"]]},{"fromName":"中国","toName":"A14","coords":[["120.19","30.26"],["22","-26"]]},{"fromName":"中国","toName":"A15","coords":[["120.19","30.26"],["115","-1"]]},{"fromName":"中国","toName":"A16","coords":[["120.19","30.26"],["-161","-47"]]},{"fromName":"中国","toName":"A17","coords":[["120.19","30.26"],["53","3"]]},{"fromName":"中国","toName":"A18","coords":[["120.19","30.26"],["102","21"]]},{"fromName":"中国","toName":"A19","coords":[["120.19","30.26"],["-33","-53"]]},{"fromName":"中国","toName":"A20","coords":[["120.19","30.26"],["3","-66"]]},{"fromName":"中国","toName":"A21","coords":[["120.19","30.26"],["-174","-33"]]}]
```javascript
option = {
  show: true,
  globeRadius: 80,
  globeOuterRadius: 85 // 设置成 81 也是一样,
  series: [
    {
      name: 'name',
      type: 'lines3D',
      coordinateSystem: 'globe',
      globeIndex: 0,
      zlevel: 1,
      effect: {
        show: true,
        period: 8,
        trailColor: '#fff',
        trailWidth: 4,
        trailLength: 0.02,
        trailOpacity: 1
      },
      lineStyle: {
        color: '#24f7f7',
        width: 2,
        opacity: 0.1
      },
      blendMode: 'lighter',
      data: dataLines
    }
  ]
}
```

### 目前效果(箭头处即超出)
![image](https://user-images.githubusercontent.com/16096736/35669432-113a0a30-0770-11e8-92c9-d269444831ce.png)

现在可以通过将 globeRadius 设置的很小来解决，但是视觉效果不佳。希望提供解决方案。感谢~

**Comment by pissang** [comment]
这个是因为你容器不够大超出视野范围了吧，可以把 globe.viewControl.distance 设置得打点

**Comment by kyriejoshua** [comment]
嗯，通过改变 distance 或者 globeRadius 都可以解决，但是也会显得 globe 在这个容器中太小。。

所以我是想通过改动类似 geo3D 中 boxHeight 这样的参数，来限制 lines3D 的高点。想确认下在 globe 中是否是 globeOuterRadius 这个参数来控制的以及如何让他生效。

**Comment by pissang** [comment]
这个暂时没法做，lines 曲度的计算考虑到了防止线和球的交叉

**Comment by kyriejoshua** [comment]
好的了解了，感谢！
