### ISSUE TITLE
gl版本与echarts 版本配合之间的问题

### ISSUE THREAD

**Issue by melodyWeb** [ecomfe/echarts-gl#195]
目前从js文件中看不出gl和echarts各为几版本，gl大概是去年十月份左右官网下的，echarts是3版本，这两个文件配合画surface类图，最后导致gl里面很多配置项无效，例如坐标轴颜色和文本颜色。换成目前gl版本的话画图异常，提示最低需要echarts4版本的才可以，换成4版本的echarts画图一切正常，但是4版本的echarts画出的其他图效果和目前所想要的效果有冲突，目前只能用3版本的echarts。请问一下3版本的echarts需要配合gl哪个区间的版本才不影响正常gl中的正常功能？

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts-gl/releases/tag/1.0.0-beta.6 这个版本之前

**Comment by houxieyu** [comment]
echarts就是个垃圾，没见过这样搞的，从文件里看不出版本

**Comment by Justineo** [comment]
@houxieyu 欢迎去使用「文件里看得出版本的项目」，不要在这个让您糟心的项目里浪费您宝贵的时间了。

**Comment by houxieyu** [comment]
@Justineo 为啥说你不好你就跑出来了，需要解决的问题一大堆，没见你回答几个

**Comment by Justineo** [comment]
@houxieyu 你这样的评论和用户就是最需要解决的问题，谢谢。
