### ISSUE TITLE
globe设置animation动画转动,如何中止动画

### ISSUE THREAD

**Issue by yanaxua** [ecomfe/echarts-gl#197]
this.earthIns.setOption({
          globe: {
            viewControl: {
              autoRotate: false,
              distance: 70,
              animation: true,/*开启过渡动画*/
              animationDurationUpdate: 3000,
              animationEasingUpdate: "linear",
              targetCoord: [113.31, 23.14]
              // targetCoord: [108.56,34.15]
            }
          }
        });

**Comment by yanaxua** [comment]
如何在动画进行过程中中止动画

**Comment by JarlRyan** [comment]
@yanaxua 你可以再加载一次setOption把动画开关的参数改成FALSE。只需要改动这个参数就可以，其它的不要重复加载 。这是我的理解，仅供参考

**Comment by yanaxua** [comment]
简单粗暴,确实可以,仔细想一想也没有必要专门开一个属性出来停止动画
