### ISSUE TITLE
echarts-x依赖的Echarts、zrender、qtek分别是什么版本

### ISSUE THREAD

**Issue by chenack** [ecomfe/echarts-gl#23]
我按照官网的方法部署的Echarts-x，运行示例的时候报了很多js文件未找到问题，是不是和版本有关，报错如下：
"NetworkError: 404 Not Found - http://localhost:8050/echarts/datavisual/echarts/src/component/dataRange.js"
dataRange.js
"NetworkError: 404 Not Found - http://localhost:8050/echarts/datavisual/echarts/src/config.js"
config.js
"NetworkError: 404 Not Found - http://localhost:8050/echarts/datavisual/zrender/src/tool/util.js"

"NetworkError: 404 Not Found - http://localhost:8050/echarts/datavisual/echarts/src/util/ecData.js"
ecData.js
"NetworkError: 404 Not Found - http://localhost:8050/echarts/datavisual/echarts/src/util/mapData/params.js"
params.js
"NetworkError: 404 Not Found - http://localhost:8050/echarts/datavisual/echarts/src/util/mapData/geoCoord.js"
geoCoord.js
"NetworkError: 404 Not Found - http://localhost:8050/echarts/datavisual/echarts/src/util/mapData/textFixed.js"
textFixed.js
"NetworkError: 404 Not Found - http://localhost:8050/echarts/datavisual/zrender/src/shape/Polygon.js"
Polygon.js
"NetworkError: 404 Not Found - http://localhost:8050/echarts/datavisual/zrender/src/shape/ShapeBundle.js"
ShapeBundle.js
"NetworkError: 404 Not Found - http://localhost:8050/echarts/datavisual/zrender/src/shape/Text.js"
Text.js
"NetworkError: 404 Not Found - http://localhost:8050/echarts/datavisual/echarts/src/chart.js"
chart.js
"NetworkError: 404 Not Found - http://localhost:8050/echarts/datavisual/echarts/src/component/base.js"
base.js
"NetworkError: 404 Not Found - http://localhost:8050/echarts/datavisual/echarts/src/util/shape/Icon.js"
Icon.js
"NetworkError: 404 Not Found - http://localhost:8050/echarts/datavisual/zrender/src/shape/Image.js"

**Comment by wjJSBlog** [comment]
version: '0.2.0',
        dependencies: {
            echarts: '2.2.1',
            zrender: '2.0.8',
            qtek: '0.2.1'
        }
