### ISSUE TITLE
echarts-x怎么把点击事件绑定到坐标点上？

### ISSUE THREAD

**Issue by fh-combo** [ecomfe/echarts-gl#25]
目前我依赖了var ecConfig = require('echarts/config');这个扩展包。
绑定方法如下：
myChart.on(ecConfig.EVENT.CLICK, function (param) {
	console.info(param);
	console.log(param.name);
	window.open('showpage.html');
});
这种方式现在只是绑定到地图区块上。
请问我有这样一个数组对象，代表坐标的经纬度。应该怎么绑定事件呢？
[{
                name: '#1 Machu Picchu, Machu Picchu, Peru',
                geoCoord: [-72.544963, -13.163141]
            }, {
                name: '#2 Angkor Wat, Siem Reap, Cambodia',
                geoCoord: [103.866986, 13.412469]
            }, {
                name: '#3 Taj Mahal, Agra, India',
                geoCoord: [78.042155, 27.175015]
            }, {
                name: '#4 Petra World Heritage Site, Wadi Musa, Jordan',
                geoCoord: [35.4428063, 30.3251545]
            },

**Comment by pissang** [comment]
正在开发新版本，会考虑这个需求，谢谢建议。
