### ISSUE TITLE
echarts how to save  image  as svg

### ISSUE THREAD

**Issue by JaosnCiCi** [ecomfe/echarts-gl#30]
saveAsImage just  support  png and jpeg. how to get svg

**Comment by helgasoft** [comment]
problem with PNG and JPG formats also, see #18470 (https://github.com/apache/echarts/issues/18470)

**Comment by AndreyPatseiko** [comment]
Problem have not resolved.
Example. https://echarts.apache.org/examples/en/editor.html?c=scatterGL-gps&gl=1&code=G4QwTgBAlgxg9gOwAogC4AsIF4BQEIDkADmugFwD0FAsgEwCctAdLQMwCsAtK6wCxMAOATE4AGJu168xLUVwCMTeaOniG8zooBsXNVq0xxo-vRm8eAGnHzauwfqtNRArZpb15AHTz5f-EdaspoqSGoryHJzM9LwazFoA7FysEgwiIQKqEibcTKyitDLyCayc_Ly0Ao4xwuJSWo6iKo4C9FVGQhaKPO0s7Frefn4wzKLyvQlarBYpotOz4xbMtFr0FuxOHAEsAvKOCeYykwldeQp5WrynCZnpTgz7QVF59Cfi9FoCufprdZmDQ38zzGpnEkw0s1YEKcxWetASnA2c3YhiUYxkK1ojlo8Jk7FEbzyByOQXQMiatEMVmpohpTgKAMBqMuwRh7FOtFErmY8nkV20yR2KJSUi-9DRCPC0nk4vUmjUvFMOKYB3kInFvOhUmCso8pwiSuYqq6CoSjKG2xi02YvAE50q7KRircxjWCQkrASqKaVw6WKMNkc8gcRn9fVRJQaAiYvH6Fi0SkyXQTwaxfKYOj2MouZp8TOjWl5Mz6a2KTA-YY-J1o_E1iLRvBgijkpWbtD28VibiCVVrMkyXsUSQa4n07KNiqWMfYVRtkws_BrXjzFtH7ARdSm-tabkDikVX0U9FYtAAwgwNrwbtwoRn2NaYi8IXwnJclowWJEePwhAAvAgANw4DgcBEKgUCINgEAAN4-AARiAMAANYAOZgHAACuCAACannAAA2cBgGQhAAMQAGaUQQFg-AAHgAgrRUAAM4kdBECoAAnkQACmJEEDAaA8ShRGcQQEAAL40fgnGMSxbEcdxfGEIJqDCaJ4lSRAPioHABFwXAtFsSuzHoHAADuJGoGAGE8dJvjkTxaAYWAymwYCzEgMAPH0cxACSAC2IAoW5EkrmF-BST4zE8WAUA8axEAANoru5Qxcbx_HMapalgAA4gAMtRK74NhaAgCRSVJbSECiAAunV9l-MxnEBQZ-EAMpQL-ymcrSJUQC1bUESRAAGJAYJQNBYrQEAFbOc1Yuwc1VMtBVYgIK0WAIo3hU1MEDRlykENlaC5YVxWAmVqAVcl1USBYtUNft-BDe1XU9ZVNY1X1jUDW9I3QPAyCkHtqWHUpWU5bFF0vRA123VVeKPfVf0ea173dcpSXfY9v1wwD-H8dZUAgAgKH4TxBBg34aV-EdUNnbFl1DAjlUDfgdOAhAoD4bZlXIxAeJo9zr0YwRH3KTY_Wi2Lw1E4QJNkxTVMc5JcOc2r-C8_zyU1cLGu-ITkskdLhty-1_GuTAqDU6LUWi1zgI69j4jskLbsi6LxtY5VZsQMo9Xm4N4sK7AiAoBgasRUMdXhT4ccSQBQA
