### ISSUE TITLE
在react中怎么引入echarts-gl呢

### ISSUE THREAD

**Issue by Dahyzeng** [ecomfe/echarts-gl#302]
在react中怎么引入echarts-gl呢
我尝试了这样引入，但会报错
![image](https://user-images.githubusercontent.com/8120004/59779784-75a18400-92eb-11e9-8456-0d0c30897367.png)
![image](https://user-images.githubusercontent.com/8120004/59779849-8f42cb80-92eb-11e9-937e-a4b851791d1c.png)

**Comment by Earlzs** [comment]
一样的错，解决了吗

**Comment by Dahyzeng** [comment]
@

**Comment by Dahyzeng** [comment]
@Earlzs 
我换成了echarts的gl就行了,按照官方文档配置一样的用
![image](https://user-images.githubusercontent.com/8120004/61120799-5522af00-a4d0-11e9-873e-da1d1ce7261f.png)
