### ISSUE TITLE
Custom series functionality on GL series

### ISSUE THREAD

**Issue by Bartvanderkruys** [ecomfe/echarts-gl#327]
Hi All,

I'm are working on a use-case where we need to render a high quantity of vectors on a WebGL layer. Is it possible to loop though all data points in a series to render a custom shape with data parameters, similarly to the custom series in echarts?

**Comment by pissang** [comment]
Hi @Bartvanderkruys . Currently ECharts GL doesn't have functionality similar to custom series in echarts. But it's a very useful feature and we are considering adding it in the future.

**Comment by Bartvanderkruys** [comment]
Thank you for the reply. I look forward to see the feature!
