### ISSUE TITLE
跨域的纹理资源有办法加载么？

### ISSUE THREAD

**Issue by sy-tang** [ecomfe/echarts-gl#33]

**Comment by pissang** [comment]
暂时没有，只能通过代理服务器，或者服务器和浏览器都设置 CORS

**Comment by pdap** [comment]
或者服务器和浏览器都设置 CORS 是什么意思？
我在服务器响应头里加上了Access-Control-Allow-Origin:* 但是浏览器如何设置CORS? ECHARTS GL 的baseTexture，heightTexture  貌似没有 配置图片 crossOrign 的地方吧？

**Comment by bluesh** [comment]
这个有解决方案嘛？
