### ISSUE TITLE
官网示例的原“微博签到点亮中国”把type改成scatterGL无法运行

### ISSUE THREAD

**Issue by SnailSword** [ecomfe/echarts-gl#34]
> 而且实现这一切只需要把原先的scatter类型改为scatterGL类型，不需要再做其它的改动！

但是把[这个例子](http://gallery.echartsjs.com/editor.html?c=scatter-weibo)中的scatter直接改成scatterGL无法运行。

**Comment by pissang** [comment]
这些前提都是文章一开始提的引入 echarts-gl 这个组件，见 http://gallery.echartsjs.com/editor.html?c=xHJkXhU9Tg 这个例子
