### ISSUE TITLE
type  从scatter 改为  scatterGL 之后 点击散点无法获取 该散点的信息   

### ISSUE THREAD

**Issue by abaozhizhong** [ecomfe/echarts-gl#35]
type 为 scatter 的时候 ，点击具体某个散点    myChart.on('click', function(data)(console.log(data)})能打印出来点击散点的信息，但是改为sctterGL后就不能够像type 为 scatter 那样，操作了

**Comment by abaozhizhong** [comment]
而且不可以像scatter那样，悬浮在上面，显示toolTip  ~~~~(>_<)~~~~泪奔

**Comment by pissang** [comment]
在列表中，谢谢建议

**Comment by gnijuohz** [comment]
顺便请问有计划支持`effectScatter`吗？

**Comment by pissang** [comment]
会支持三维的 effectScatter3D，但是二维的散点图主要用来加速大规模散点图的绘制，所以暂时不考虑。

不过这个并不会影响你 effectScatter 和 scatterGL 的混用

**Comment by gnijuohz** [comment]
目前在尝试globe图，所以有些好有没有类似geo图的那种（用effectScatter达到的）ripple effect效果。期待effectScatter3D！

谢谢回复！很赞的库！👍👍👍

**Comment by pissang** [comment]
@gnijuohz 谢谢，计划中了 :)
