### ISSUE TITLE
npm 上 echarts 和 echarts-gl latest 版本不匹配。

### ISSUE THREAD

**Issue by cnwhy** [ecomfe/echarts-gl#362]
现在npm上
- `echarts`  latest 4.9.0
- `echarts-gl` latest 2.x

导致常规安装 `echarts-gl` 后，echarts 4.x 上加载 `echarts-gl` 报错

**Comment by Mrzr666** [comment]
这个问题搞了我一下午，看源码发现和echarts版本对不上，只好来git上下载1.1.2的echarts-gl换上去了，希望官方尽快修复吧

**Comment by pissang** [comment]
抱歉已修复

**Comment by cnwhy** [comment]
辛苦了 @pissang

**Comment by Volankey** [comment]
npm直接发布了2.0.0.rc.1,那1.2.0不发布了么? @pissang
