### ISSUE TITLE
npm上直接发布了2.0.0-rc.1,版本1.1.2呢

### ISSUE THREAD

**Issue by Volankey** [ecomfe/echarts-gl#366]
npm上直接发布了2.0.0-rc.1,版本1.1.2呢
![image](https://user-images.githubusercontent.com/23287363/99039821-fe951b80-25c2-11eb-86f7-15af23308678.png)

**Comment by Epictek** [comment]
Not an issue? That is the RC release for the next branch to go along with the next release of echarts (5.0.0-rc.1)

See here https://github.com/ecomfe/echarts-gl/blob/next/package.json

**Comment by Volankey** [comment]
But the version of  latest release  is 1.1.2
![image](https://user-images.githubusercontent.com/23287363/102881153-63c41280-4487-11eb-9ba3-1fa81e824f71.png)

In the npm, i can't find the version(1.1.2)
https://www.npmjs.com/package/echarts-gl

**Comment by pissang** [comment]
@Volankey Sorry, I just published it.
