### ISSUE TITLE
TypeError: Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by Chinamonster123** [ecomfe/echarts-gl#384]
when both use echarts@5.0.0 and echarts-gl@2.0.0 in a vue program, this problem would happen. however, use echarts@4.x.x and echarts-gl@1.x.x instead. this problem would not appear.

**Comment by pissang** [comment]
Please update to echarts@5.0.1

**Comment by Chinamonster123** [comment]
> Please update to echarts@5.0.1

it makes sense , thanks 😀
