### ISSUE TITLE
Graph GL with ForceAtlas2 strange beheaviour when zooming or interacting.

### ISSUE THREAD

**Issue by fornasari12** [ecomfe/echarts-gl#385]
I have a graph of approximately 4k nodes, which is embedded in a web platform. When refreshing the web or updating visualization the graph broken as you can see in the following image:

![Screen Shot 2021-01-22 at 09 36 36](https://user-images.githubusercontent.com/57304126/105491695-7a7fa400-5c95-11eb-9909-6734ea6510d3.png)

If I restart visuals it fixes until further interaction with the graph (tooltip, toolbox, zoom in/zoom out):

![Screen Shot 2021-01-22 at 09 36 54](https://user-images.githubusercontent.com/57304126/105491750-95eaaf00-5c95-11eb-8243-0a72aa63b652.png)

My forceAtlas settings:

"forceAtlas2": {
                            "steps": 5,
                            "stopThreshold": 20,
                            "jitterTolerence": 10,
                            "edgeWeight": [0.2, 1],
                            "gravity": 500,
                            "edgeWeightInfluence": 1,
                            "scaling": 150,
                            "repulsionByDegree": False,
                            "linLogMode":False,
                            "GPU": True
}

I could give more detail if needed, @pissang!

Thks

**Comment by Gykonik** [comment]
Did you find out the problem? :D

**Comment by nappernick** [comment]
For me? Use another option. This is for a specific data type - [network/relational data](https://echarts.apache.org/en/option-gl.html#series-graphGL). The others were the correct choice for my graphs, even with load.
