### ISSUE TITLE
echarts4.9 echarts-gl 2.02 build出现如下错误

### ISSUE THREAD

**Issue by leiqu** [ecomfe/echarts-gl#393]
ERROR in ./~/_echarts-gl@2.0.2@echarts-gl/lib/component/grid3D/Grid3DAxis.js
Module not found: Error: Can't resolve 'echarts/lib/label/labelStyle' in 'E:\source\flying-fish-manage\node_modules\_echarts-gl@2.0.2@echarts-gl\lib\component\grid3D'
 @ ./~/_echarts-gl@2.0.2@echarts-gl/lib/component/grid3D/Grid3DAxis.js 2:0-63
 @ ./~/_echarts-gl@2.0.2@echarts-gl/lib/component/grid3D/Grid3DView.js
 @ ./~/_echarts-gl@2.0.2@echarts-gl/lib/component/grid3D/install.js
 @ ./~/_echarts-gl@2.0.2@echarts-gl/lib/component/grid3D.js
 @ ./~/_echarts-gl@2.0.2@echarts-gl/lib/export/all.js
 @ ./~/_echarts-gl@2.0.2@echarts-gl/index.js
 @ ./src/main.js

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts-gl#include-by-scripts

> ECharts GL 2.x is compatible with ECharts 5.x. ECharts GL 1.x is compatible with ECharts 4.x.
