### ISSUE TITLE
使用MAPBOX3D 报错

### ISSUE THREAD

**Issue by mezp** [ecomfe/echarts-gl#398]
chart.setoption 之后

![1](https://user-images.githubusercontent.com/20810607/111744726-a484c980-88c6-11eb-9b47-693086fbd28c.jpg)
版本：
 "echarts": "^5.0.2",
 "echarts-gl": "^2.0.2",
 "mapbox-gl": "^1.13.1",

**Comment by daima1111** [comment]
我也是用mapbox3D报错，在series中加上coordinateSystem: 'mapbox3D',就报此错误。

**Comment by pissang** [comment]
刚发布了 2.0.4 修复了这个问题

**Comment by daima1111** [comment]
@pissang 谢谢您！我升级了echarts-gl，版本为2.0.4，报错解决，并且正常出图。
