### ISSUE TITLE
Animate globe.viewControl changes 

### ISSUE THREAD

**Issue by jarben** [ecomfe/echarts-gl#40]
This is probably part of the animation/transition roadmap but just to emphasise - would be nice if dynamic changes in  globe.viewControl are animated so that globe would animate to different position if changed dynamically. 

Also, might be good to have a way to set geo coordinates rather than numbers for alpha/beta?

**Comment by pissang** [comment]
Good point! Will consider these two suggestions.

**Comment by pissang** [comment]
Add transitions of view in https://github.com/ecomfe/echarts-gl/commit/6d2ba51efea63dff39233aadfec82c30e536aa03.

About geo coordinates. Is it ok with you to use following option?

```js
viewControl: {
   longitude: 116.46,
   latitude: 39.92
}
```

**Comment by jarben** [comment]
Just tested the view transition, works great!

Regarding geo coordinates, your suggesting is perfectly fine, just wondering whether it's coherent with echarts where it's usually an array? Maybe coords:[lat, long]?

**Comment by pissang** [comment]
I was just struggling between array and separate properties.  I think `coords: [long, lat]` is better now.

**Comment by jarben** [comment]
Sounds good!

**Comment by pissang** [comment]
Add `targetCoord` property finally.
