### ISSUE TITLE
echarts-gl@2之后的版本支持mapbox-gl吗？

### ISSUE THREAD

**Issue by daima1111** [ecomfe/echarts-gl#400]

**Comment by pissang** [comment]
支持的

**Comment by daima1111** [comment]
echarts@5.0.2
echarts-gl@2.0.2
mapboxgl@1.12.0
在使用mapbox3D时报错
报错信息
![image](https://user-images.githubusercontent.com/72121519/113974343-541edd00-9870-11eb-9b14-0b4dcafc3d4a.png)

**Comment by pissang** [comment]
刚发布了 2.0.4 修复了这个问题

**Comment by daima1111** [comment]
@pissang 谢谢您！我升级了echarts-gl，版本为2.0.4，报错解决，并且正常出图。
