### ISSUE TITLE
echarts4升级5废弃了scale，换成scaleX,scaleY。

### ISSUE THREAD

**Issue by daima1111** [ecomfe/echarts-gl#401]
官网特效气泡图的涟漪效果会报警告。
![image](https://user-images.githubusercontent.com/72121519/113978804-fd68d180-9876-11eb-9982-e2ad5c311f26.png)
echartspei'zhi配置项中并没有配置scale等参数。应该怎么配置呢？

**Comment by pissang** [comment]
这个应该是内部没有完全替换掉老的接口的 warning，可以忽略，后面版本会修正
