### ISSUE TITLE
鼠标移上去之后Bar3Dzhu柱状图之后，坐标轴上的信息没有消失！

### ISSUE THREAD

**Issue by panxiaochao** [ecomfe/echarts-gl#42]
![image](https://cloud.githubusercontent.com/assets/5567405/25377428/2057fa32-29da-11e7-9575-feec164e1c58.png)
如图所示

**Comment by pissang** [comment]
是什么时候没有消失？

**Comment by panxiaochao** [comment]
是移出画布的时候，还有，这个柱状图不是可以用轮滚放大放小，但是在一加载的时候，有时候太大，有没有参数是可以定轮滚的级别的？

**Comment by pissang** [comment]
https://ecomfe.github.io/echarts-doc/public/cn/option-gl.html#grid3D.viewControl.distance 可以通过 `distance`，`minDistance`, `maxDistance` 控制缩放距离
