### ISSUE TITLE
Cut down file size published on npm

### ISSUE THREAD

**Issue by fuzhenn** [ecomfe/echarts-gl#43]
Hi, @pissang 

首先要表达一下敬仰，这个库做的真心赞！ 一定要找个时间好好学习一下。 :smile_cat: 

我注意到echarts-gl发布到npm上的文件比较多， 体积也比较大，除了dist目录， src目录也被发布到了npm上， 感觉有了dist，应该就不再需要src， 是否考虑把src从npm中去掉？

**Comment by pissang** [comment]
谢谢，其实 webpack 打包使用到的是 src 下的模块，可以按需加载。

**Comment by fuzhenn** [comment]
收到，close
