### ISSUE TITLE
dataShape is not provided. Guess it is [ ]

### ISSUE THREAD

**Issue by xiansh** [ecomfe/echarts-gl#431]
1.1.2版本，`series.data`赋值后，控制台会打印：`dataShape is not provided. `，而且guess值与实际传递的值不符。

**Comment by lukaskupczyk** [comment]
I experience the same issue. Where is the "dataShape" parameter documented?

**Comment by xiansh** [comment]
文档没有dataShape说明，可以在series中直接加这个字段，填写数据大小

**Comment by lukaskupczyk** [comment]
Could you clarify what should be provided as the dataShape? Thank you.

**Comment by lukaskupczyk** [comment]
Thank you for your help. My data is the following for a surface Chart:

` [[45000, 30, 367],
[50000, 30, 372],
[55000, 30, 375],
[60000, 30, 375],
[65000, 30, 375]]`

I would therefore suppose that I got 3 columns and 5 rows. Setting these values results in a warning:
`GL_INVALID_OPERATION: Vertex buffer is not big enough for the draw call`

The suggested value is [1,5].

When I add a row:
`[
    [45000, 30, 367],
    [50000, 30, 372],
    [55000, 30, 375],
    [60000, 30, 375],
    [65000, 30, 375],
    [65000, 30, 375],
  ]`

The suggestion is [2,3].

Your help is very much appreciated.

**Comment by lukaskupczyk** [comment]
Hi,
any updates on this?

Thank you!
