### ISSUE TITLE
eachOtherLayer is not a function error

### ISSUE THREAD

**Issue by ob-ARC** [ecomfe/echarts-gl#438]
When switching an echart instance from SVG rendering to canvas rendering, external_echarts_.registerPostInit will throw an error because it tries to invoke this.eachOtherLayer, which only exists on the canvas renderer, but not on the SVG renderer. I wonder if this related to the "Hack" comment above the declaration of registerPostInit?

PS: I am not an expert on JS, but as a workaround I simply added a check of

if (!(this.eachOtherLayer === undefined))

in front of the problematic code, which seems to work just fine.

**Comment by pedrolamas** [comment]
I'm seeing this issue too on a Vue app:

![image](https://user-images.githubusercontent.com/85504/155894469-15b81d43-b1d3-48b0-847d-b618ce1b7dfb.png)

What I don't get is where this [eachOtherLayer](https://github.com/ecomfe/echarts-gl/blob/5ad547afd0c63e3021d131998919319ac5623c3e/src/echarts-gl.js#L176) function is supposed to be defined... as I can't find it anywhere!

**Comment by matmen** [comment]
eachOtherLayer is [part of zrender](https://github.com/ecomfe/zrender/blob/e6d458c1e7bfeeb1949b3462d3a7d48d8dea12fc/src/canvas/Painter.ts) and only exists for the CanvasPainter class. The SVGPainter doesn't implement it at all.I believe this is just an oversight, and can be fixed with a simple type check.

**Comment by pedrolamas** [comment]
I've confirmed locally that a simple check to see if the function is defined before actually invoking it will fix this problem, so I've now submitted a Pull Request with that exact change in it.
