### ISSUE TITLE
加入echarts-gl.js后echarts其他图表series中的itemStyle不生效

### ISSUE THREAD

**Issue by yu501954162** [ecomfe/echarts-gl#46]
您好，我咋加入echarts-gl.js后echarts其他图表series中的itemStyle属性不生效，是添加方式的问题还是需要更改某些配置？

**Comment by pissang** [comment]
最新版本应该已经修复这个问题

**Comment by pissang** [comment]
https://github.com/ecomfe/echarts/issues/5669#issuecomment-299385856
