### ISSUE TITLE
例子中，Scatter3D 某些点会被遮挡

### ISSUE THREAD

**Issue by duchengyao** [ecomfe/echarts-gl#508]
比如下面视频最左边的绿点，会挡在蓝点的前面。

能否告知是哪里的原因我可以修改并提PR

[Screencast from 10-19-2023 05:39:04 PM.webm](https://github.com/ecomfe/echarts-gl/assets/7941237/f1040a34-05d9-48cb-a8b6-5dd50f61ab83)

**Comment by duchengyao** [comment]
可能有关的 issues

https://github.com/ecomfe/echarts-gl/issues/504

https://github.com/ecomfe/echarts-gl/issues/475

https://github.com/ecomfe/echarts-gl/issues/222

**Comment by helgasoft** [comment]
possible duplicate of #464

**Comment by clddup** [comment]
什么情况 怎么解决啊 怎么就关闭了? 大佬们
