### ISSUE TITLE
echartsGL:3Dbar和散点图等，visualMap控件鼠标hover时无效果

### ISSUE THREAD

**Issue by BeginVic** [ecomfe/echarts-gl#54]
问题：visualMap控件鼠标hover时无效果
希望得到的效果：visualMap控件鼠标hover时，可以像2D图一样，对应值的数据有浮动效果。
官网问题实例： https://github.com/ecomfe/echarts-gl

**Comment by pissang** [comment]
最新版本 1.0.0-alpha.4 应该不存在这个问题

**Comment by BeginVic** [comment]
https://github.com/ecomfe/echarts-gl/tree/1.0.0-alpha.4/dist
你好，我引用这两个js文件，依然没有效果。
![Uploading B2[ZRY7LJOHW[P5C@RYZ30L.png…]()
图中A处鼠标hover，B处对应数据柱触发

**Comment by pissang** [comment]
@BeginVic 图片上传失败了

**Comment by BeginVic** [comment]
https://github.com/ecomfe/echarts-gl/tree/66f6cd3a543b4d5f08bc3c313eb9e11292646aed/dist
可以提供一下这两个脚本的链接吗？（因为看到是你发布的哈）
我在上面新建一下项目，你再帮我看一下。
可以吗~

**Comment by pissang** [comment]
https://rawgit.com/ecomfe/echarts-gl/master/dist/echarts-gl.min.js 或者  https://rawgit.com/ecomfe/echarts-gl/master/dist/echarts-gl.js

**Comment by BeginVic** [comment]
http://gallery.echartsjs.com/editor.html?c=xH1abYrSlW&v=1
这个是按你的脚本新建的项目，依然没有效果。你看看是什么问题？

**Comment by pissang** [comment]
了解了，下个版本改进

**Comment by BeginVic** [comment]
好的

**Comment by hashlinyk** [comment]
beta.6貌似也有这个问题
