### ISSUE TITLE
echarts-gl 浏览器支持情况

### ISSUE THREAD

**Issue by love3forever** [ecomfe/echarts-gl#57]
我在尝试使用echarts-gl的时候，发现IE11里边提示浏览器不支持Webgl，请问这是什么原因导致的
另外，我用ie11打开http://pissang.github.io/dota2hero/#/hero/invoker 这个站点的时候，是可以正常显示的

**Comment by love3forever** [comment]
另外，echarts[官网示例](http://gallery.echartsjs.com/explore.html#sort=rank~timeframe=all~author=all)在IE11下也不能显示

**Comment by pissang** [comment]
每个例子都无法显示？

**Comment by love3forever** [comment]
感谢你的回复。并不是所有的例子都无法显示，我发现使用了echarts-gl的例子，比如[三维柱状图](http://gallery.echartsjs.com/editor.html?c=xSJUxZ-c6x)还有[三维地球](http://gallery.echartsjs.com/editor.html?c=xSk7XrQKpl)这样的都无法正常显示。

**Comment by pissang** [comment]
可能跟 https://github.com/ecomfe/echarts-gl/issues/102 这个是相同的问题，已修复

**Comment by love3forever** [comment]
嗯 ，问题解决了！我刚把项目最新代码拿下来编译，发现qtek版本的依赖必须0.4.1，发现https://www.npmjs.com还没有这个版本，需要自己手动编译，总之，辛苦大神啦🙏
