### ISSUE TITLE
Geo3D 组件的事件参数没有 name 等有用的信息

### ISSUE THREAD

**Issue by pissang** [ecomfe/echarts-gl#58]

**Comment by xiaomijiayou** [comment]
我的代码有问题吗， 还是没有获取到事件， 能把您的测试事件的代码给我看下吗

**Comment by pissang** [comment]
http://gallery.echartsjs.com/editor.html?c=xHyaMMrFx-&v=2

**Comment by xiaomijiayou** [comment]
我 npm install echarts-gl@ 1.0.0-alpha.5  获取到的eharts-gl.min.js  是不能获取到事件的， 使用了您的例子加载的echarts-gl.min.js 是可以获取到click事件， 确实没有可用信息， 地区点击事件做不到了

**Comment by xiaomijiayou** [comment]
谢谢您的认真解答， 这个问题什么时候可以更新

**Comment by pissang** [comment]
奇怪了，我看看为什么 npm 不行，这个下个版本修复，估计两周后

**Comment by xiaomijiayou** [comment]
你好， 这个问题的修复版本出来了吗， 具体什么时间可以使用

**Comment by pissang** [comment]
大概这周四会发布 1.0.0-alpha.6 ，到时候会修复这个问题

**Comment by xiaomijiayou** [comment]
您好， 请问 .6的发布在哪里

**Comment by pissang** [comment]
@xiaomijiayou https://github.com/ecomfe/echarts-gl/releases/tag/1.0.0-alpha.6 ，npm 上也已经更新，你试下

**Comment by xiaomijiayou** [comment]
试了一下再html单页里可以， 但是放在react 中无法显示，
代码如下， 没有报错，就是没有生成canvas
componentDidMount : function(){

        $.get( '/static/json/henan.json', function (mapJson) {
            this.setState({mapJson: mapJson});
        }.bind(this));

       
    },


    render: function() {
        if(this.state.mapJson){
            // this.getOtion();

        var name ="henan";
        echarts.registerMap('henan', this.state.mapJson);

        var chart = echarts.init(document.getElementById('data-vi-content'));

        chart.setOption({
                backgroundColor: '#cdcfd5',
                geo3D: {
                    map: 'henan',
                    shading: 'lambert',
                    realisticMaterial: {
                        roughness: 0.2,
                        metalness: 0
                    },
                    postEffect: {
                        enable: true
                    },
                    groundPlane: {
                        show: true
                    },
                    light: {
                        main: {
                            intensity: 1,
                            shadow: true,
                            shadowQuality: 'high',
                            alpha: 30
                        },
                        ambient: {
                            intensity: 0
                        },
                        ambientCubemap: {
                            exposure: 2,
                            diffuseIntensity: 0.3
                        }
                    },
                    viewControl: {
                        distance: 50
                    },

                    itemStyle: {
                        borderColor: '#222',
                        borderWidth: 1
                    }
                },
                series: []
            });

        }
        return null;
    }

**Comment by xiaomijiayou** [comment]
旧版本是可以的

**Comment by pissang** [comment]
@xiaomijiayou 你看下控制台有没有报 warning 什么的？

**Comment by xiaomijiayou** [comment]
echarts.js:6064     Method `dispose` should be implemented in custom.
  index.html:1    [.Offscreen-For-WebGL-0000000008188350]RENDER WARNING: there is no texture bound to the unit 0   
就这两个 警告，

**Comment by pissang** [comment]
那应该不是 init 的问题，项目能否发我看下？

**Comment by xiaomijiayou** [comment]
问题找到了， 我使用官网下载的echarts 3.6.1  地图无法显示， 当时有 npm install echarts@3.6.1 ， import echarts  时地图可以正常显示， 但是会报很多 警告：[.Offscreen-For-WebGL-0000000011DE80B0]RENDER WARNING: there is no texture bound to the unit 0

问题有点奇怪

**Comment by pissang** [comment]
是有点奇怪，能否发我下能够复现的项目？我看一下原因

**Comment by huangwenxuan** [comment]
如何通过action触发toolbox里datazoom的区域缩放功能，而不是用鼠标点击？？

**Comment by qianbaiduhai** [comment]
大佬，我现在在vue里面也事获取不到事件啊

**Comment by maicWorkGithub** [comment]
@pissang 
`Loaded qtek, version 0.4.3` 和 `Loaded claygl, version 1.3.0`是换了引擎么，用你给的链接里的`echart-gl`点击能触发事件，最新版的，就是使用了`claygl`的不行

**Comment by ThomasXing** [comment]
> 是有点奇怪，能否发我下能够复现的项目？我看一下原因

问题找到了， 我使用官网下载的echarts 3.6.1 地图无法显示， 当使用 npm install echarts@3.6.1 ， import echarts 时地图可以正常显示， 但是会报很多 警告：[.Offscreen-For-WebGL-0000000011DE80B0]RENDER WARNING: there is no texture bound to the unit 0

这个警告我再2.0.0中也出现了，并且geo3d点击不触发

**Comment by Huauauaa** [comment]
anything new?
