### ISSUE TITLE
地球自动旋转问题

### ISSUE THREAD

**Issue by anderzhuo** [ecomfe/echarts-gl#61]
Echarts-x的官方案例中，地球会自动旋转，鼠标点击延迟几秒后地球会继续自动旋转。可是在github上下载了案例在本地运行。鼠标点击后就不再自动旋转。这是为什么？另外，Echarts-x的相关帮助太少了，没有Echarts多。各种看不懂啊

**Comment by pissang** [comment]
可以设置 http://echarts.baidu.com/option-gl.html#globe.viewControl.autoRotateAfterStill
