### ISSUE TITLE
geo3D 的itemStyle.normal.color 不支持渐变色和纹理填充

### ISSUE THREAD

**Issue by xiaomijiayou** [ecomfe/echarts-gl#62]
geo支持 color：渐变色和纹理填充，
geo3D 不支持， 感觉功能不太对应

**Comment by pissang** [comment]
一套是 Canvas 二维的，一套是 WebGL 三维的，肯定配置上会有出入，我们只能尽量在大部分配置上做到统一。

就拿你说的渐变和纹理来说，geo3D 中有更强大的材质配置参数去配置这些效果。

https://ecomfe.github.io/echarts-doc/public/cn/option-gl.html#geo3D.realisticMaterial

**Comment by xiaomijiayou** [comment]
好的， 谢谢，明白了
