### ISSUE TITLE
globe可以动态添加数据吗.

### ISSUE THREAD

**Issue by yuanzhaokang** [ecomfe/echarts-gl#63]
比如说，我要开一个websocket，接受即时的数据，可以动态渲染吗？ 我没找到相应的接口. 谢谢.

**Comment by pissang** [comment]
http://echarts.baidu.com/tutorial.html#%E5%BC%82%E6%AD%A5%E6%95%B0%E6%8D%AE%E5%8A%A0%E8%BD%BD%E5%92%8C%E6%9B%B4%E6%96%B0
