### ISSUE TITLE
折线图显示underfined问题

### ISSUE THREAD

**Issue by langwuzhe** [ecomfe/echarts-gl#68]
在做折线图的时候，为什么当data：[null,null,null] 这样的数组的时候,有的图上会显示一条"-",但是有的图会显示underfined
![qq 20170525161612](https://cloud.githubusercontent.com/assets/24667395/26442063/90f26b90-4165-11e7-8eea-90f889f799e0.jpg)
![qq 20170525161626](https://cloud.githubusercontent.com/assets/24667395/26442070/959acafc-4165-11e7-91f2-cec2f2c164e2.jpg)

**Comment by pissang** [comment]
请在 https://github.com/ecomfe/echarts  提 issue
