### ISSUE TITLE
geo3D 和 map3D 地图的问题

### ISSUE THREAD

**Issue by jwister** [ecomfe/echarts-gl#69]
geo3d  map属性 用其它省份的地方能够出来 ，但是 用china地图  控制台就抛出错误  
Uncaught TypeError: Cannot read property 'y' of null 

我仔细看了下地图的js  发现省份的地方 和那种中国的地图坐标加密的方式 是不是不一样啊？ 使用 geo3d  要如果 使用中国地图。  

map3D  使用中国地图也有同样的问题。  但是 使用其它的省份的地图又都没问题。

**Comment by pixcai** [comment]
遇到同样的问题了。不仅单个渲染中国地图出错，用geo3d渲染世界地图时，中国的区域也没有绘制出来。希望作者能快速解决这个问题。

**Comment by pissang** [comment]
能否在 http://gallery.echartsjs.com/ 建一个例子

**Comment by pixcai** [comment]
例子：http://gallery.echartsjs.com/editor.html?c=xByP5xZG4W&comment=0

**Comment by pissang** [comment]
这个可能是因为 gallery 上地图文件有点老不兼容的缘故，我们更新下，你也可以试下 https://github.com/ecomfe/echarts/tree/master/map/js  上最新的地图文件

**Comment by pissang** [comment]
Gallery 中已修复

**Comment by luguokong** [comment]
官网上的http://echarts.baidu.com/download-map.html 中国地图还是无法使用，不过地图数据在线生成工具生成的地图是好的。

另外问一句：地图数据在线生成工具是故意设置不让下载中国地图吗？

if (INIT_PROVINCE_CONTENT.indexOf($('#province').val()) > -1) {
            return;
}

**Comment by Yang1998cmd** [comment]
map如何设置某个省份

**Comment by JoeYoungFang** [comment]
> 这个可能是因为 gallery 上地图文件有点老不兼容的缘故，我们更新下，你也可以试下 https://github.com/ecomfe/echarts/tree/master/map/js 上最新的地图文件

下载的world.json和world.js文件乱码是怎么回事
![image](https://user-images.githubusercontent.com/19636215/101713380-8131cd80-3ad2-11eb-8e11-edc93d314eda.png)

**Comment by luguokong** [comment]
@JoeYoungFang 这个是对地图坐标做了压缩处理，不是乱码

**Comment by zning02** [comment]
3D 中国地图为什么无法显示南海诸岛

**Comment by lijianmincn** [comment]
我也遇到这个问题了，请问解决了吗？

**Comment by seed-fe** [comment]
> 3D 中国地图为什么无法显示南海诸岛

遇到了同样的问题，请问解决了吗？
