### ISSUE TITLE
引入demo出错

### ISSUE THREAD

**Issue by Togal** [ecomfe/echarts-gl#76]
#### 在下面的地址里，并没有chart目录哦
![image](https://user-images.githubusercontent.com/9533360/26868035-129c035c-4b9a-11e7-9807-4e6ea667fc22.png)。

**Comment by pissang** [comment]
建议用最新的 ECharts GL，http://echarts.baidu.com/blog/2017/04/12/echarts-gl-alpha.html

**Comment by Togal** [comment]
好的，谢谢您的回答！

**Comment by Togal** [comment]
@pissang 大大，还有个问题，请问echarts GL 兼容echarts2、echarts3版本吗？

**Comment by pissang** [comment]
使用最新的 echarts 3 版本

**Comment by Togal** [comment]
好的，谢大大细心回答。
