### ISSUE TITLE
Geo3D下的bar3d定位不准确

### ISSUE THREAD

**Issue by zhenglingfei** [ecomfe/echarts-gl#79]
http://gallery.echartsjs.com/editor.html?c=xrJdvs1oRx
如官网示例，柱状图会位于geo3d之下，我的项目也出现了这个问题。
另：
现在是否支持Geo3d下的柱状图tooltip？
谢 @pissang

**Comment by zhenglingfei** [comment]
是否是由于多次初始化或者旋转镜头之后再setoption造成的呢

**Comment by pissang** [comment]
bar3D 的定位会忽略每块区域单独的高度，统一基于 reigionHeight
