### ISSUE TITLE
Geo3D下更新data后数据bar3d定位不准确

### ISSUE THREAD

**Issue by zhenglingfei** [ecomfe/echarts-gl#85]
很抱歉没有及时回复，我新建了一个实例，在setoption之后，bar3D的位置就不准确了，不知是否是插件问题还是我这边更新数据的方式的问题，谢谢 @pissang 
http://gallery.echartsjs.com/editor.html?c=xr1Oxy_DNW&v=2

**Comment by pissang** [comment]
应该是个 bug，谢谢反馈

**Comment by zhenglingfei** [comment]
恩,感谢.27352行geo3DLayout的coordSys.dataToPoint似乎有些问题,暂时通过写死start值使用
