### ISSUE TITLE
GraphGL在力导向布局中动画bug

### ISSUE THREAD

**Issue by Slept-Warrior** [ecomfe/echarts-gl#91]
## 问题描述
在[该实例](http://gallery.echartsjs.com/editor.html?c=xrJ1Udzj4Z)中，力导向布局的图表**在渲染后约1s后动画停止**，**此时若点击图例按钮则动画继续0.5-1s**。（另，图例按钮点击后变灰但该图例分类类目的节点不会消失/显现）
[该实例](http://gallery.echartsjs.com/editor.html?c=xrJ1Udzj4Z)是一个与我实际工程实现类似的Demo，由于我实际使用情境中节点数量过大，不适于应用Echarts-Graph关系图（会造成浏览器假死）。

## 版本及环境
JS: ECharts 3.6.2, ECharts GL 1.0.0-alpha
Browser: Chrome 59.0.3071.104/ Forefox 54.0/IE10
OS: Win7 Ult SP1/ Win10 Pro 1703/ Ubuntu 16.04.2 (Kernel 4.8.0-58)

## 我的配置和截图
配置如[该实例](http://gallery.echartsjs.com/editor.html?c=xrJ1Udzj4Z)，在不同系统的不同浏览器测试后结果相同，故不予截图。

## 期望结果
- 提供一个在当前版本可用的临时解决方案
- 在后续版本中解决此问题

**Comment by pissang** [comment]
之前看过你这个例子，这个是因为 stopThreshold 设置的过大导致布局提前结束了，你可以试试设置成 0.001

```js
forceAtlas2:{
                preventOverlap: true,
                scaling: 15,
                stopThreshold: 1e-3
            }
```

**Comment by Slept-Warrior** [comment]
感谢，问题已经得到临时解决。
请问该实例中并无stopThreshold设置，是默认值的问题吗？

**Comment by pissang** [comment]
是的
