### ISSUE TITLE
echarts-gl 安装不了

### ISSUE THREAD

**Issue by leapoct** [ecomfe/echarts-gl#92]
[~] $ npm install echarts-gl
npm ERR! code ETARGET
npm ERR! notarget No matching version found for qtek@0.4.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'echarts-gl'
npm ERR! notarget

**Comment by hon** [comment]
是的，同样的问题。

**Comment by pissang** [comment]
Sorry 没有发现 npm 上没发布成功，现在已经发布了
