### ISSUE TITLE
请问map3D下的立体建筑物对应的geoJSON如何获得

### ISSUE THREAD

**Issue by jiangbai333** [ecomfe/echarts-gl#95]
我在使用echarts制作一个立体地图应用，遇到了这个问题，例子我看懂了，但是不知道在切换城市后，如何获得对应的立体geoJSON数据。
请问是需要自己来制作么？

**Comment by pissang** [comment]
我是从 https://mapzen.com/documentation/vector-tiles/layers/#buildings-and-addresses 获取的

**Comment by sncer** [comment]
可以获取中国地区的建筑GeoJSON数据吗？还是需要自己通过什么工具制作？

**Comment by pissang** [comment]
@sncer 可以的，但是中国区的会有很多缺失

**Comment by chris2go** [comment]
从gaode 抓

**Comment by pissang** [comment]
@chris2go 掉渣！

**Comment by cenkai88** [comment]
@chris2go 请问能具体说下如何抓么？没看到接口啊

**Comment by chris2go** [comment]
没有接口 ，从下面来的，像素坐标http://vector.amap.com/vector/buildings?tiles=105197,52241&level=17
 
 

 发件人： cenkai发送时间： 2017-09-12 14:31收件人： ecomfe/echarts-gl抄送： chris2go; Mention主题： Re: [ecomfe/echarts-gl] 请问map3D下的立体建筑物对应的geoJSON如何获得 (#95)@chris2go 请问能具体说下如何抓么？没看到接口啊

**Comment by parksben** [comment]
https://github.com/parksben/amap-building-crawler

**Comment by knowbyyou** [comment]
请问有什么地方可以找到比较全的中国区的GeoJson数据？？比如北京市这种。

**Comment by hopkinson** [comment]
![image](https://user-images.githubusercontent.com/13248613/37078942-dbefcd26-221b-11e8-9374-af80f747aea4.png)
我在dataV看到，请问圈住的效果应该怎么样实现，可以提供一个思路？

**Comment by wandergis** [comment]
@hopkinson

**Comment by dfy167** [comment]
大哥，就没有取一份全国的？...有的话给我一份啊...Q120853467

**Comment by alex2wong** [comment]
@hopkinson  这种可以通过domOverlay 来实现，就是叠加一个dom元素，一条线一个圆点，比如：https://alex2wong.github.io/mapbox-plugins/examples/chartlayer/ 图表下面的指示线就是dom 元素

**Comment by emugod1101** [comment]
http://vector.amap.com/vector/buildings?tiles=105197,52241&level=17 
现在访问得到的是空值，请问是什么情况？
